version: '3.8'

services:
  test-enhanced:
    build:
      context: .
      dockerfile: Dockerfile.test-enhanced
    container_name: btc-test-enhanced
    environment:
      - PYTHONPATH=/app/src/backend
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
    command: >
      bash -c "
        echo '=== Testing Enhanced LSTM Module Imports ===' &&
        python test_enhanced_imports.py &&
        echo '' &&
        echo '=== Running Enhanced LSTM Integration Tests ===' &&
        pytest tests/integration/test_enhanced_lstm.py -v
      "