services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: btc-trading-backend
    ports:
      - "8080:8000"
    volumes:
      - ./storage/data:/app/data
      - ./storage/models:/app/models
      - ./storage/logs/backend:/app/logs
      - ./storage/config:/app/config
    environment:
      - DATABASE_PATH=/app/data/trading_system.db
      - MODEL_PATH=/app/models
      - LOG_PATH=/app/logs
      - CONFIG_PATH=/app/config
      - PYTHONUNBUFFERED=1
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
    networks:
      - trading-network
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: btc-trading-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./storage/logs/frontend:/app/logs
      - ./storage/config:/app/config
    environment:
      - API_BASE_URL=http://backend:8000
      - LOG_PATH=/app/logs
      - CONFIG_PATH=/app/config
      - PYTHONUNBUFFERED=1
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - trading-network
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  trading-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  btc_data:
    driver: local
  btc_models:
    driver: local
  btc_logs:
    driver: local